---
- name: call config check
  hosts: all
  #become: true
  tasks:
    
    - name: Copy Dockerfile
      copy:
        src: ../Dockerfile
        dest: "/docker"

    - name: Run command to build image
      command: docker build --tag blog /docker/

    - name: Run command to create container
      command: docker run --name blog -p 80:8000 -it blog bash