---
- name: call config check
  hosts: all
  become: true
  tasks:

    - name: Wait 300 seconds, but only start checking after 60 seconds
      wait_for_connection:
        delay: 60
        timeout: 300

    # Chown filesystems
    - name: Set docker directory
      file:
        path: "/docker"
        state: directory
        mode: '777'
    
    - name: Copy file 
      copy:
        src: ../install-docker-ubuntu.sh
        dest: "/docker"

    - name: Run a script to install Docker
      command: sh /docker/install-docker-ubuntu.sh

    - name: Add user to Docker Group
      command: usermod -aG docker "{{ user_docker }}"