---
- name: call config check
  hosts: all
  become: true
  tasks:

    - name: Wait for SSH to come up
      wait_for: host={{ azure_instance_ip }} port=22 delay=60 timeout=320 state=started

    # Chown filesystems
    - name: Set docker directory
      file:
        path: "/docker"
        state: directory
        mode: '777'
    
    - name: Copy file 
      copy:
        src: ../install-docker-ubuntu.sh
        dest: "/docker"

    - name: Run a script to install Docker
      command: sh /docker/install-docker-ubuntu.sh

    - name: Add user to Docker Group
      command: usermod -aG docker "{{ user_docker }}"