---
- name: call config check
  hosts: all
  become: true
  tasks:
    
    - name: Copy file 
      copy:
        src: ../install-docker-ubuntu.sh
        dest: /

    - name: Run a script
      script: /install-docker-ubuntu.sh